### ISSUE TITLE
[FEAT] Meta-Model Iteration 2

### ISSUE THREAD

**Issue by Radu-Nicolae** [Radu-Nicolae/opendc#16]
### 🚀 Meta-Model

**📝 Summary:**
Enhance and maximize the performance, clarity, and functionality of the Meta-Model.

**🔍 Detailed Description:**
TODO LIST
- [x] Output the Meta-Model's prediction
- [x] Plot the Meta-Model with the Multi-Model
- [x] Implement a (good) mathematical meta-function
- [x] Build an accuracy analyzer tool 
- [x] Documented code for both Multi-Meta-Model

**💡 Use Case:**
Built on top of RQ1 (Multi-Model), used for RQ2 and, further, for RQ3.

**🔄 Possible Alternatives:**
N/A

**📌 Additional Context:**
N/A

**🔗 Linked Branch:**
[branch-name](https://github.com/user/repo/tree/branch-name)
Todo add branch here ^
